openapi: 3.0.0
info:
  title: Médiathèque API
  version: 1.0.0
  description: API pour gérer une médiathèque
servers:
  - url: http://localhost:3000

paths:
  /api/users:
    get:
      summary: Liste tous les utilisateurs
      responses:
        "200":
          description: Liste d'utilisateurs

  /api/resources:
    get:
      summary: Liste toutes les ressources
      responses:
        "200":
          description: Liste de ressources

  /api/emprunts:
    get:
      summary: Liste tous les emprunts
      responses:
        "200":
          description: Liste d'emprunts
